version: '3.0'

services:
  webserver:
    container name: firstProject.web
    build:
      context: .
      dockerfile: DockerFile.web
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80



  app:
    cotainer_name: firstProject-app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
